language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test
  - DATABASE_URL_TEST=postgres://utpwsugatpqjzn:03120a462667a671da3979385da1b5650ab8082d1319630013ec707eb7338ca5@ec2-54-225-173-42.compute-1.amazonaws.com:5432/ddo2ssbhau003c
  - SECRET=teamwork-api-secret-key

before_script:
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage