CREATE TABLE IF NOT EXISTS users (
    ID VARCHAR PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    storedUserEmail VARCHAR(255) NOT NULL UNIQUE,
    hashedPassword VARCHAR(400) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    jobRole VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS articles (
    ID INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    article text NULL,
    createdOn VARCHAR NOT NULL,
    authorId VARCHAR REFERENCES users(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS gifs (
    ID INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    gifURL VARCHAR NOT NULL,
    gifPublicId VARCHAR NOT NULL,
    createdOn VARCHAR NOT NULL,
    authorId VARCHAR REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    ID INTEGER PRIMARY KEY,
    comment text NOT NULL,
    createdOn VARCHAR NOT NULL,
    authorId VARCHAR REFERENCES users(ID) ON DELETE CASCADE,
    articleId INTEGER REFERENCES articles(ID) ON DELETE CASCADE,
    gifId INTEGER REFERENCES articles(ID) ON DELETE CASCADE
);